name = "novel-site"
pages_build_output_dir = "."
compatibility_date = "2026-02-25"

[[d1_databases]]
binding = "DB"
database_name = "novel-db"
database_id = "8598c21d-c3a9-47f4-b2d6-2e7cb455720f"

[[r2_buckets]]
binding = "R2"
bucket_name = "novel-storage"
